spring:
  application:
    name: eureka-server-application

server:
  port: 8083
eureka:
  dashboard:
    path: '${EUREKA_PATH:/}'
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8083/eureka}
