apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-dep
  labels:
    app: discovery-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discovery-api
  template:
    metadata:
      labels:
        app: discovery-api
    spec:
      containers:
        - image: javasre2022/discovery
          imagePullPolicy: Always
          name: discovery-api
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-service
spec:
  selector:
    app: discovery-api
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
